# Site settings
title: "Anand Singh Shekhawat"
email: anandsingh215@yahoo.com
description: "A dark blog theme for Jekyll."
baseurl: ""
url: "httss://shekhawat2.github.io/"
title_description: ""
title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
google_analytics: "UA-20365477-4"
disqus_account: Shekhawat2
github_repository: https://github.com/shekhawat2
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: A_S_Shekhawat
github_username:  Shekhawat2
instagram_username: anand_shekhawat11
reddit_username: 
linkedin_link:
google_plus_link:
stackoverflow_link:
xing_link:
facebook_link: https://facebook.com/anand.anandsinghshekhawat

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://facebootk.com/anand.anandsinghshekhawat\">Anand Shekhawat</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/Shekhawat2\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
