import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import GestureLayout from "../components/GestureLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Anand Singh Shekhawat",
  description: "Generated by Anand",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Navbar */}
        <Navbar />

        {/* GestureLayout - Wraps only the animated content */}
        <div className="min-h-screen">
          <GestureLayout>{children}</GestureLayout>
        </div>

        {/* Footer - Fixed at the bottom, outside of GestureLayout */}
        <Footer />
      </body>
    </html>
  );
}
